*Numpy (numerical python)*

Porque estudar numpy:
 -Eficiência em calculos numericos
 -Ferramenta open source
 -Referência no desenvolvimento de outras bibliotecas.


Recursos principais do numpy:
 -Arrays
 -Operações rápidas 
 -Estatistica descritiva
 -Manipulação de dados
 -Valores de constantes matemáticas

**NdArrays**

-Os arrays tem o tipo definido (tipos únicos, ou listas do mesmo tamanho);
-Não pode ser alterado

*Propriedades*

-Shape: Estrutura em relação as suas dimenções

-Ndim: Quantidade de dimenções

-Dtype: Tipo dos elementos


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]], int);

arr.shape

(2, 3)

In [7]:
arr.ndim

2

In [8]:
arr.dtype

dtype('int64')

In [12]:
arr = np.zeros((2, 2), int)
arr

array([[0, 0],
       [0, 0]])

In [16]:
arr = np.identity(3) #Valores iguais na diagonal principal
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Computação Vetorizada**

 - Aritimética
 Operações entre arrays: Soma,Sub,Mult,Div entre ndArrays do mesmo tamanho element to element

 Operações com escalares: Something but in all elements

 -Comparações
 -Indexação e fatiamento

In [5]:
arr1 = np.arange(5)
arr2 = np.arange(5, 10) 
print(arr1)
print(arr2)

[0 1 2 3 4]
[5 6 7 8 9]


In [9]:
# faz somatória sem precisar de loop
arr1 + arr2

array([ 5,  7,  9, 11, 13])

In [11]:
arr1 * 2

array([0, 2, 4, 6, 8])

In [14]:
arr1 = np.array([1, 3, 5, 7, 8, 10]);
arr2 = np.array([2, 0, 4, 6, 9, 11])

arr1 < arr2

array([ True, False, False, False,  True,  True])

In [15]:
arr1 >5

array([False, False, False,  True,  True,  True])

In [19]:
(arr1 > 2) & (arr1 < 8)

array([False,  True,  True,  True, False, False])

In [25]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr[1]

array([4, 5, 6])

In [ ]:
arr[1, 1]

np.int64(5)

In [29]:
arr[0, 1:3]

array([2, 3])

In [30]:
arr[1, :]

array([4, 5, 6])

In [31]:
arr[:, 1]

array([2, 5, 8])

In [33]:
arr_uni = arr[(arr > 3) & (arr < 7)]
arr_uni

array([4, 5, 6])

*Fazer modificação de fatiamento em referencias alteram o valor original do array, tomaer sempre cuidado, quando não quiser modificar o valor original usar o .copy()*

**Estatística para numpy**

_Estatisticas descritivas_

- Medidas de tendencias cetrais
  média, moda, mediana e percentil -> Percentil é uma medida que divide um conjunto de dados em 100 pates iguais.
- Valores limites
- Desvio padrão -> O desvio padrão é uma medida de quanto os valores variam em relação a média | se os desvio padrão for baixo os valores estão mais próximos da média se for alto eles estou espalhados. 
- Somatório -> soma e soma acumulativa


In [3]:
arr = np.linspace(0, 20, 21);
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [4]:
# média

arr.mean()

np.float64(10.0)

In [5]:
arr.max()

np.float64(20.0)

In [6]:
arr.min()

np.float64(0.0)

In [8]:
# indice onde o valor máximo foi encontrado e onde o valoor minímo foi encontrado
print(arr.argmax())

print(arr.argmin())

20
0


In [11]:
# desvio padrão 

print(arr.std())

6.0553007081949835


In [12]:
arr.sum()

np.float64(210.0)

In [13]:
arr.cumsum()

array([  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.,  55.,
        66.,  78.,  91., 105., 120., 136., 153., 171., 190., 210.])

In [14]:
#Exercicio: Selecione os valores que se distanciam da média até o desvio padrão 

bool_idx = (arr > arr.mean() - arr.std()) & (arr < arr.mean() + arr.std())

print(arr[bool_idx])

[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


**Funções universais do Numpy**

São funções vetorizadas que podem operar de maneira eficientes arrays N-dimencioais (ndArrays) elemento a elemento, são escritas em C.

*uFuncs*


In [16]:
#mediana

print(np.median(arr))

10.0


In [17]:
print(np.percentile(arr, 45))

9.0


In [18]:
#seno
arr2 = np.array([0, np.pi /2])

np.sin(arr2)

array([0., 1.])

In [19]:
#Maximum -> Valor maximo de cada posição

arr_1 = np.array([3, 8, 32, 2, 54, 17])
arr_2 = np.array([ 9, 11, 63, 22, 0, 41])

np.maximum(arr_1, arr_2)

array([ 9, 11, 63, 22, 54, 41])

In [22]:
#Valores pseudoaleatórios

arr = np.random.uniform(0, 10, 6)
print(arr)
print()
print(np.modf(arr))

[4.78943987 2.14937279 7.59368909 3.92146595 4.92069052 4.95468666]

(array([0.78943987, 0.14937279, 0.59368909, 0.92146595, 0.92069052,
       0.95468666]), array([4., 2., 7., 3., 4., 4.]))


**Álgebra Linear** 

 - Algebra linear é uma área da matemática que se foca no estudo de vetores, espaços vetoriais e transfomaçõe lineares.

 - Entender e manipular vetores e matrizes são fundamentais para análise e manipulação de dados.

 - Ndarrays 
 -Podemos criar vetores e matrizes través de um objeto ndarray
 -O numpy oferece múltipas feramentas para manipulação de vetores e matrizes
 Ex: 
    -Adição, subtração
    -Multiplicação por escalar
    -Multiplicação de matrizes
    -Cálculo de determinante
    -Transposição
    -Inverção de matriz


In [23]:
#Outra forma de criar matrizes indentidade 

mtx = np.eye(3) + [1, 1.5, 3]
print(mtx)

[[2.  1.5 3. ]
 [1.  2.5 3. ]
 [1.  1.5 4. ]]


In [25]:
vet = np.array([1, 2, 3])
vet

array([1, 2, 3])

In [26]:
#Multiplicação de matrizes: .dot e @
mtx.dot(vet)

array([14., 15., 16.])

In [27]:
mtx @ vet

array([14., 15., 16.])

In [29]:
#Determinante
print(np.linalg.det(mtx))

6.500000000000001


In [30]:
#Transposição de uma matriz

mtx.T

array([[2. , 1. , 1. ],
       [1.5, 2.5, 1.5],
       [3. , 3. , 4. ]])

In [31]:
#Matriz inversa

np.linalg.inv(mtx)

array([[ 0.84615385, -0.23076923, -0.46153846],
       [-0.15384615,  0.76923077, -0.46153846],
       [-0.15384615, -0.23076923,  0.53846154]])